name: "Count approval"

on:
  pull_request_review:
    types: [submitted]

permissions:
  contents: read
  pull-requests: write

jobs:
  labels:
    runs-on: ubuntu-latest
    if: "github.repository_owner == 'NixOS' && !contains(github.event.pull_request.title, '[skip treewide]')"
    steps:
    - name: List reviews on the pull request
      shell: bash
      run: |
        token=${{ secrets.GITHUB_TOKEN }}
        base64AuthInfo='$token | base64 -e'
          response=$(curl --request GET \
            --url https://api.github.com/repos/${{ github.repository }}/pulls/${{ github.event.pull_request.number }}/reviews \
            --header 'Authorization: $base64AuthInfo' \
            --header 'Content-Type: application/json')

        echo $response | jq '.[] | select(.state=="APPROVED")'
